import { NextRequest, NextResponse } from "next/server"
import { supabase } from "@/lib/store"
import { checkAdminSecret } from "@/lib/api-auth"
import { createHash, randomBytes } from "crypto"
import { sendApiKeyRegeneratedEmail } from "@/lib/email"

export async function POST(request: NextRequest) {
  const authError = checkAdminSecret(request)
  if (authError) return authError

  try {
    const { keyId } = await request.json()
    if (!keyId) return NextResponse.json({ error: "keyId is required" }, { status: 400 })

    // Get the existing key record
    const { data: existing } = await supabase
      .from("api_keys")
      .select("*")
      .eq("id", keyId)
      .maybeSingle()

    if (!existing) return NextResponse.json({ error: "Key not found" }, { status: 404 })

    // Revoke the old key
    await supabase
      .from("api_keys")
      .update({ active: false, revoked_at: new Date().toISOString(), revoke_reason: "Regenerated by admin" })
      .eq("id", keyId)

    // Generate a new key
    const rawKey = `bxl_live_${randomBytes(32).toString("hex")}`
    const keyHash = createHash("sha256").update(rawKey).digest("hex")
    const keyPrefix = rawKey.slice(0, 16)

    const { data: newKey, error } = await supabase
      .from("api_keys")
      .insert({
        company_name: existing.company_name,
        contact_email: existing.contact_email,
        mc_number: existing.mc_number,
        key_hash: keyHash,
        key_prefix: keyPrefix,
        active: true,
        can_post: existing.can_post,
        can_update: existing.can_update,
        can_delete: existing.can_delete,
        total_requests: 0,
      })
      .select()
      .single()

    if (error) throw error

    // Email the broker their new key
    await sendApiKeyRegeneratedEmail({
      to: existing.contact_email,
      contactName: existing.contact_name || existing.company_name,
      companyName: existing.company_name,
      apiKey: rawKey,
    })

    return NextResponse.json({ success: true, newKeyId: newKey.id })
  } catch (err) {
    console.error("Regenerate key error:", err)
    return NextResponse.json({ error: "Failed to regenerate key" }, { status: 500 })
  }
}